    user  nginx;
    worker_processes  auto;
    error_log  /var/log/nginx/error.log warn;
    pid        /var/run/nginx.pid;

    events {
        worker_connections  1024;
    }

    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;

        log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                        '$status $body_bytes_sent "$http_referer" '
                        '"$http_user_agent" "$http_x_forwarded_for"';

        access_log  /var/log/nginx/access.log  main;

        sendfile        on;
        #tcp_nopush     on;

        keepalive_timeout  65;

        #gzip  on;

        include /etc/nginx/conf.d/*.conf;

        server {
            listen 80;  # Thay đổi từ 4200 thành 80 để khớp với cấu hình Docker Compose
            server_name localhost;

            location / {
                root /usr/share/nginx/html;  # Thay đổi đường dẫn root để trỏ đến thư mục chứa ứng dụng Angular
                index index.html index.htm;
                try_files $uri $uri/ /index.html;
            }

            error_page 404 /404.html;
            location = /404.html {
                internal;
            }

            location /api {
                proxy_pass https://localhost:8443/api;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;

                proxy_ssl_verify off;

                add_header Access-Control-Allow-Origin *;
                add_header Access-Control-Allow-Methods 'GET, POST, OPTIONS';
                add_header Access-Control-Allow-Headers 'Origin, Authorization, Accept, Content-Type';
            }
        }
    }
